post:
  tags:
    - Product and Variant
  summary: Add / Update Variant Aggregator Settings
  description: This can only be done by the logged in user.
  operationId: addVariantSettings
  responses:
    '200':
      description: OK
    '400':
      description: >-
        You will get a pair of `error_code` and `error_message`. [Handling
        Errors](/developer-portal/handling-errors/#product-and-variant)
  security:
    - Stamps_APIToken: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\VariantSettings.yaml
