post:
  tags:
    - Group
  summary: Add / Update Group Aggregator Settings
  description: ''
  operationId: addGroupSettings
  responses:
    '200':
      description: OK
    '400':
      description: >-
        You will get a pair of `error_code` and `error_message`. [Handling
        Errors](/developer-portal/handling-errors/#group)
  security:
    - Stamps_APIToken: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\GroupSettings.yaml
