post:
  tags:
    - Modifier
  summary: Add / Update Modifier Aggregator Settings
  description: This can only be done by the logged in user.
  operationId: addModifierSettings
  responses:
    '200':
      description: OK
    '400':
      description: >-
        You will get a pair of `error_code` and `error_message`. [Handling
        Errors](/developer-portal/handling-errors/#modifier)
  security:
    - Stamps_APIToken: []
  requestBody:
    content:
      application/json:
        schema:
          $ref: ..\components\schemas\AddModifier.yaml
