openapi: 3.0.3
servers:
  - url: 'https://staging-omni.stamps.id'
info:
  description: >-
    This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).  For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Overview
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: Inventory
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: 'http://swagger.io'
  - name: Group
    description: Access to Petstore orders
  - name: Order
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
  - name: Product and Variant
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
  - name: Modifier
    description: Operations about user
    externalDocs:
      description: Find out more about our store
      url: 'http://swagger.io'
paths:
  /api/backend/inventories/update:
    post:
      tags:
        - Inventory
      summary: Add / Update Inventory
      description: ''
      operationId: addInventory
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#inventory)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/AddInventory'
  /api/backend/inventories/update-out-of-stock:
    post:
      tags:
        - Inventory
      summary: Update Out of Stock Inventory
      description: ''
      operationId: updateInventory
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#inventory)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/OosInventory'
  /api/backend/inventories/aggregator-settings/update:
    post:
      tags:
        - Inventory
      summary: Add / Update Inventory Aggregator Settings
      description: Multiple status values can be provided with comma separated strings
      operationId: addInventorySettings
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#inventory)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/InventorySettings'
  /api/backend/groups/update:
    post:
      tags:
        - Group
      summary: Add / Update Group
      description: Returns a map of status codes to quantities
      operationId: addGroup
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#group)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/AddGroup'
  /api/backend/groups/aggregator-settings/update:
    post:
      tags:
        - Group
      summary: Add / Update Group Aggregator Settings
      description: ''
      operationId: addGroupSettings
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#group)
      security:
        - Stamps_APIToken:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GroupSettings'
  /api/store/orders/get:
    get:
      tags:
        - Order
      summary: Get Order
      description: This can only be done by the logged in user.
      operationId: getOrder
      responses:
        '200':
          description: successful operation
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
  /api/store/orders/details:
    get:
      tags:
        - Order
      summary: Get Order Details
      description: ''
      operationId: getOrderDetails
      responses:
        '200':
          description: successful operation
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/OrderDetails'
  /api/store/orders/paid:
    post:
      tags:
        - Order
      summary: Paid Order
      description: ''
      operationId: paidOrder
      responses:
        '200':
          description: successful operation
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/Orders'
  /api/store/orders/complete:
    post:
      tags:
        - Order
      summary: Complete Order
      description: ''
      operationId: completeOrder
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/CompleteOrder'
  /api/store/orders/confirm:
    post:
      tags:
        - Order
      summary: Confirm Order
      description: ''
      operationId: confirmOrder
      responses:
        '200':
          description: successful operation
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/Orders'
  /api/store/orders/cancel:
    post:
      tags:
        - Order
      summary: Cancel Order
      description: ''
      operationId: cancelOrder
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
      requestBody:
        $ref: '#/components/requestBodies/Orders'
  /api/mobile/orders/add:
    post:
      tags:
        - Order
      summary: Add Order
      description: This can only be done by the logged in user.
      operationId: addOrder
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#order)
      security:
        - Stamps_APIToken:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddOrder'
        description: Updated user object
        required: true
  /api/backend/products/update:
    post:
      tags:
        - Product and Variant
      summary: Add / Update Product & Variant
      description: This can only be done by the logged in user.
      operationId: addProduct
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#product-and-variant)
      security:
        - Stamps_APIToken:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddProduct'
        description: Updated user object
        required: true
  /api/backend/products/variants/aggregator-settings/update:
    post:
      tags:
        - Product and Variant
      summary: Add / Update Variant Aggregator Settings
      description: This can only be done by the logged in user.
      operationId: addVariantSettings
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#product-and-variant)
      security:
        - Stamps_APIToken:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VariantSettings'
  /api/backend/groups/set-variants:
    post:
      tags:
        - Product and Variant
      summary: Add / Update Variant Group
      description: This can only be done by the logged in user.
      operationId: addVariantGroup
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#product-and-variant)
      security:
        - Stamps_APIToken:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddVariant'
  /api/backend/modifier-groups/aggregator-settings/update:
    post:
      tags:
        - Modifier
      summary: Add / Update Modifier Aggregator Settings
      description: This can only be done by the logged in user.
      operationId: addModifierSettings
      responses:
        '200':
          description: OK
        '400':
          description: You will get a pair of `error_code` and `error_message`. [Handling Errors](/developer-portal/handling-errors/#modifier)
      security:
        - Stamps_APIToken:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddModifier'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
components:
  responses:
    PetResponse:
      description: successful operation
      content:
        application/xml:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AddInventory'
        application/json:
          schema:
            type: array
            items:
              $ref: '#/components/schemas/AddInventory'
  requestBodies:
    AddInventory:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AddInventory'
        application/xml:
          schema:
            $ref: '#/components/schemas/AddInventory'
      description: ""
      required: true
    OosInventory:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OosInventory'
    InventorySettings:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/InventorySettings'
    AddGroup:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AddGroup'
    OrderDetails:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/OrderDetails'
    Orders:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Orders'
    CompleteOrder:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/CompleteOrder'
    AddOrder: 
      content: 
        application/json:
          schema:
            $ref: '#/components/schemas/AddOrder'
  securitySchemes:
    Stamps_APIToken:
      description: API Token Provided by Stamps, please contact Stamps if you have not received your token.
      type: apiKey
      name: PRIVATE-TOKEN
      in: header
  schemas:
    AddProduct:
      type: object
      properties:
        code:
          type: char
        name:
          type: char
        display_name:
          type: char
        short_description:
          type: char
        description:
          type: char
        markdown_description:
          type: string
        position:
          type: float
        inventory_enabled:
          type: boolean
    GetOrder:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        password:
          type: string
        phone:
          type: string
        userStatus:
          type: integer
          format: int32
          description: User Status
      xml:
        name: User
    Inventories:
      type: object
      properties:
        variant_code:
          type: char
        price:
          type: float
        out_of_stock: 
          type: boolean
        is_active: 
          type: boolean
      xml:
        name: Category
    AddInventory:
      type: object
      properties:
        store_code:
          type: char
        inventories:
          $ref: '#/components/schemas/Inventories'
      xml:
        name: Pet
    OosInventory: 
      type: object
      properties:
        store: 
          type: char
        code: 
          type: char
        out_of_stock:
          type: boolean
    InventorySettings: 
      type: object
      properties:
        is_active:  
          type: boolean
        variant_code: 
          type: char
        price:
          type: int
        discounted_price:
          type: float
    AddGroup: 
      type: object
      properties:
        code:  
          type: char
        name: 
          type: char
        parent:
          type: char
        is_active:
          type: boolean
    GroupSettings:
      type: object
      properties:
        group:
          type: string
        is_active:
          type: boolean
        type:
          type: string
        name:
          type: char
        position:
          type: int
        description:
          type: char
        aggregator_category_id:
          type: char
    VariantSettings:
      type: object
      properties:
        is_active:
          type: boolean
        variant_code:
          type: char
        type:
          type: string
        code:
          type: char
        sku:
          type: char
        name:
          type: char
        position:
          type: int
        default_price:
          type: float
        description:
          type: char
    AddVariant:
      type: object
      properties:
        code:
          type: char
        sku:
          type: char
        name: 
          type: char
        display_name:
          type: char
        description:
          type: char
        markdown_description:
          type: string
        groups:
          type: string
        position:
          type: float
        dimension:
          type: string (JSON)
        extra_data:
          type: string (JSON)
    AddModifier:
      type: object
      properties:
        is_active: 
          type: boolean
        position:
          type: int
    OrderDetails:
      type: object
      properties:
        last_order_id:
          type: char
    Orders:
      type: object
      properties:
        order: 
          type: char
    CompleteOrder:
      type: object
      properties:
        order: 
          type: char
        receiver_name:
          type: char
        received_time:
          type: string
        payment_method:
          type: string
    AddOrder:
      type: object
      properties:
        notes: 
          type: char
        payment_method:
          type: string
        channel:
          type: string
        type:
          type: string
        queue_number:
          type: char
        table_number:
          type: char
        status:
          type: string
