openapi: 3.0.3
info:
  description: >-
    This is a sample server Petstore server.  You can find out more about
    Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/).  For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Overview
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://staging-omni.stamps.id
tags:
  - name: Inventory
    description: Inventory settings and modifications
  - name: Group
    description: Group settings and modifications
  - name: Order
    description: Order settings and modifications
  - name: Product and Variant
    description: Product and Variant settings and modifications
  - name: Modifier
    description: Modifier settings
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
paths:
  /api/backend/inventories/update:
    $ref: paths/api_backend_inventories_update.yaml
  /api/backend/inventories/update-out-of-stock:
    $ref: paths/api_backend_inventories_update-out-of-stock.yaml
  /api/backend/inventories/aggregator-settings/update:
    $ref: paths/api_backend_inventories_aggregator-settings_update.yaml
  /api/backend/groups/update:
    $ref: paths/api_backend_groups_update.yaml
  /api/backend/groups/aggregator-settings/update:
    $ref: paths/api_backend_groups_aggregator-settings_update.yaml
  /api/store/orders/get:
    $ref: paths/api_store_orders_get.yaml
  /api/store/orders/details:
    $ref: paths/api_store_orders_details.yaml
  /api/store/orders/paid:
    $ref: paths/api_store_orders_paid.yaml
  /api/store/orders/complete:
    $ref: paths/api_store_orders_complete.yaml
  /api/store/orders/confirm:
    $ref: paths/api_store_orders_confirm.yaml
  /api/store/orders/cancel:
    $ref: paths/api_store_orders_cancel.yaml
  /api/mobile/orders/add:
    $ref: paths/api_mobile_orders_add.yaml
  /api/backend/products/update:
    $ref: paths/api_backend_products_update.yaml
  /api/backend/products/variants/aggregator-settings/update:
    $ref: paths/api_backend_products_variants_aggregator-settings_update.yaml
  /api/backend/groups/set-variants:
    $ref: paths/api_backend_groups_set-variants.yaml
  /api/backend/modifier-groups/aggregator-settings/update:
    $ref: paths/api_backend_modifier-groups_aggregator-settings_update.yaml
components:
  securitySchemes:
    Stamps_APIToken:
      description: >-
        API Token Provided by Stamps, please contact Stamps if you have not
        received your token.
      type: apiKey
      name: PRIVATE-TOKEN
      in: header
