name: test-deploy

# Run on each push to master
on:
  push:
    branches: [ fix-docs ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Testing private usage
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2

      - name: redoc-cli test
        uses: ./ # Uses an action in the root directory
        with:
          args: 'bundle openapi/omniapi.yaml -o omniapi.html'

      - name: check result
        run: |
          ls -al
          test -f omniapi.html || (echo "Missing petstore.html from previous step." && exit 1)

  test_job_2:
    runs-on: ubuntu-latest
    name: Testing public name
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # use the public name of the action
      - name: redoc-cli test
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle openapi/omniapi.yaml -o omniapi.html'

      - name: check result
        run: |
          ls -al
          test -f omniapi.html || (echo "Missing petstore.html from previous step." && exit 1)