name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
#       - name: cd to root folder
#         run: cd ${{ github.workspace }}/openapi
      - name: Convert YAML to HTML
        run: npx @redocly/cli build-docs openapi/omniapi.yaml -o index.html
      - name: List files
        run: ls -R
