name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Redocly CLI
        run: npm install -g @redocly/cli
      - name: cd to root folder
        run: cd ${{ github.workspace }}
      - name: Convert YAML to HTML
        run: npx @redocly/cli build-docs omniapi.yaml
